### ISSUE TITLE
Mahalanobis Distances in groupPCA

### ISSUE THREAD

**Issue by niknikos** [zarquon42b/Morpho#4]
Hi and thanks for this great package. I was wondering whether it is possible (or even correct) one to get Mahalanobis distances as an output in groupPCA, as returned by CVA in package Morpho. I have given the code of both functions (as well as the called CVAdists.r code) but I am too unskilled to implement such changes to the code in order to get the desired result...  

Thanks

**Comment by zarquon42b** [comment]
there is no Mahalanobis distances in groupPCA, because the space is not scaled according to the covariance structure.
You can simply use CVA, to get (groupwise) Mahalanobisdistances based on the pooled-within group covariance matrix.
Or do you want to compute per-specimen distances to all group means?

**Comment by niknikos** [comment]
Ok, that pretty much answers my question. I had already obtained the groupwise mah distances from the CVA, but I just didn't know whether it would be correct to obtain them from the groupPCA as well. Thank you for the clarifications :)
